name: mockerywebpro-deploy

on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Set up build number
        id: vars
        run: echo ::set-output name=BUILD_NUMBER::$(echo $GITHUB_RUN_NUMBER)
      - name: Generate random tag
        id: random_tag
        run: echo ::set-output name=RANDOM_TAG::$(echo $(($(date +%s%N) % 10000))-${{ steps.vars.outputs.BUILD_NUMBER }}-${RANDOM})
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/mockerywebpro:latest

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker Login to ACR
        run: docker login ${{ secrets.ACR_ENDPOINT }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
      - name: Pull Docker image
        run: docker pull ${{ secrets.ACR_ENDPOINT }}/mockerywebpro:latest
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mockery-web-pro-staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        env:
          NEXT_PUBLIC_AZURE_AD_B2C_TENANT_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_AD_B2C_TENANT_NAME }}
          NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID }}
          NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_SECRET }}
          NEXT_PUBLIC_AZURE_AD_B2C_PRIMARY_USER_FLOW: ${{ secrets.NEXT_PUBLIC_AZURE_AD_B2C_PRIMARY_USER_FLOW }}
          NEXT_PUBLIC_MOCKERY_BASEURL: ${{ secrets.NEXT_PUBLIC_MOCKERY_BASEURL }} 
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
